A. Ans: let element1=['hydrogen','H',1.008];
let element2=['helium','He',4.003];
let element3=['iron','Fe',55.85];
console.log(element1,element2,element3);
B.  Ans: let element1=['hydrogen','H',1.008];
let element2=['helium','He',4.003];
let element3=['iron','Fe',55.85];
let table=[];
table.push(element1);
table.push(element2);
table.push(element3);
console.log(table);
C. Ans: let element1=['hydrogen','H',1.008];
let element2=['helium','He',4.003];
let element3=['iron','Fe',55.85];
let table=[];
table.push(element1);
table.push(element2);
table.push(element3);
console.log(table[1][1]);
D. Ans: let element1=['hydrogen','H',1.008];
let element2=['helium','He',4.003];
let element3=['iron','Fe',55.85];
let table=[];
table.push(element1);
table.push(element2);
table.push(element3);
console.log(table[0][2],table[1][0],table[2][1]);
